name: Deploy to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "Brandons DO Environment"  # <-- Set this to match your environment name

    steps:
      - name: Echo environment variable
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          IP_ADDRESS: ${{ vars.IP_ADDRESS }}
        run: echo "This is a manual run - $DROPLET_IP"
       
      - name: Echo environment variable2
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          echo "This is a manual1 run - ${{ secrets.DROPLET_IP }}"
          echo "hey? ${{ secrets.PRIVATE_KEY }}"
          echo "hey? ${{ secrets.PRIVATE_KEY2 }}"
          echo "hey? $IP_ADDRESS"
          echo "hey? ${{ vars.IP_ADDRESS }}"
