name: Deploy to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "Brandons DO Environment"  # <-- Set this to match your environment name

    steps:
      - name: Echo environment variable
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: echo "This is a manual run - $DROPLET_IP"
       
      - name: Echo environment variable2
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          echo "This is a manual1 run - ${{ secrets.DROPLET_IP }}"
          echo "hey? $MY_PUBLIC_VARIABLE"
