name: Deploy to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "Brandons DO Environment"  # <-- Set this to match your environment name

    steps:
      - name: Echo environment variable
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          IP_ADDRESS: ${{ vars.IP_ADDRESS }}
        run: echo "This is a manual run - $DROPLET_IP"
       
      - name: Echo environment variable2
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          IP_ADDRESS: ${{ vars.IP_ADDRESS }}
        run: |
          echo "This is how you access a secret (it won't display in echo though) --> ${{ secrets.PRIVATE_KEY }}"
          echo "For a regular environment be sure to set the 'environment' under deploy --> ${{ vars.IP_ADDRESS }}"
          echo "Or maybe? $IP_ADDRESS"

      - name: SSH and list files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.IP_ADDRESS }}
          username: summershades
          key: ${{ secrets.PRIVATE_KEY }}
          script: ls -la
